version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/var/www/html                # PHP kaynak kodlarınızı bağlamak için
      - ./docker/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini # XDebug ayarlarını bağlamak için
    ports:
      - "8080:80"                          # Apache için HTTP port yönlendirmesi
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=42815"
    networks:
      - webnet

networks:
  webnet:
