version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/var/www/html                # PHP kaynak kodlarınızı bağlamak için
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini # XDebug ayarlarını bağlamak için
    ports:
      - "8080:80"                          # Apache için HTTP port yönlendirmesi
      - "42568:42568"
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    networks:
      - webnet

networks:
  webnet:
